package sentence;

import logicalreasoner.inference.Inference;
import logicalreasoner.truthfunction.TruthAssignment;

import java.util.ArrayList;

/**
 * The Sentence class represents any type of logical
 * Sentence, (ie. Constant, Atom, Predicate, or generated by connectives)
 */
public abstract class Sentence {
    protected ArrayList<Sentence> args;
    protected String name;

    protected Sentence(ArrayList<Sentence> a, String n) {
        args = new ArrayList<>(a);
        name = n;
    }

    public abstract Boolean eval(TruthAssignment h);

    public abstract Inference reason(TruthAssignment h, int inferenceNum);

    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("(").append(name);
        args.forEach(arg -> builder.append(" ").append(arg));
        builder.append(")");
        return builder.toString();
    }

    public int hashCode() { return toString().hashCode(); }

    public boolean equals(Object o) {
        if (o instanceof Sentence) {
            Sentence s = (Sentence)o;
            if (!s.name.equals(name) || s.args.size() != args.size())
                return false;

            for (int i = 0; i < args.size(); ++i) {
                if (!args.get(i).equals(s.args.get(i)))
                    return false;
            }

            return true;
        }
        return false;
    }

    public int numArgs() {
        return args.size();
    }

    public int size() {
        return args.stream().mapToInt(Sentence::size).sum() + numArgs();
    }
}
